### PR TITLE
Add flag for showing full bundle install log output

### PR DESCRIPTION
**Pull request by jhoward321**
This adds a flag for showing the full bundle install log. I will add a separate PR for skipping deployment.

### CODE REVIEW

**Comment by jhoward321** [comment]
#8 Might be a cleaner solution for this problem

**Comment by EdricChan03** [comment]
Superseded by #8.

**Comment by EdricChan03** [comment]
I'll be reconsidering this PR.

**Comment by jhoward321** [comment]
@EdricChan03 I rebased to include the new changes. That being said, I would love to have this also incorporate the logic from #8 . I strongly believe there is no good reason to ever suppress a failed build. That defeats the purpose of a build.

**Comment by EdricChan03** [comment]
@jhoward321 Maybe you could include that suggestion in a further PR?

**Pull request merged**
